### ISSUE TITLE
Supervised Methods

### ISSUE THREAD

**Issue by wuweia123** [xingyuuchen/freq-aware-depth#2]
Thanks for your wonderful work! Did you try to use your method in supervised MDE ，will it be effective？

**Comment by xingyuuchen** [comment]
Hello @wuweia123 ,

Thanks for your interest!
We are sorry that we did not try our method in supervised MDE. In my personal opinion, the methods in this paper are to solve the general problems in the specific photometric loss function used in self-supervised training. I.e., our methods do not have much to do with the supervised ones.

However, I'm not very sure, this is just a suggestion, you can also have a try.

Best,
Xingyu
